version: '3'
services:
  db:
    image: postgres:11.4-alpine
  web:
    image: elixir:1.10.1-alpine
    command: sh -c 'mix local.hex --force && mix phx.server'
    links:
      - db
    ports: 
      - 4000:4000
    volumes:
      - .:/work
    working_dir: /work
