version: '3'
services:
  db:
    image: postgres:11.4-alpine
    ports:
      - 5432:5432
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: mix phx.server
    links:
      - db
    ports: 
      - 4000:4000
    volumes:
      - .:/work
    working_dir: /work
